# Generated by Django 4.2.23 on 2025-07-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
